---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/ci-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
