---
name: Update Versions List Gist
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          set-safe-directory: ${{ github.workspace }}
      - uses: iamsauravsharma/create-dotenv@v2.0.1
        with:
          file-path: '/tmp/.env'
        env:
          GITHUB_TOKEN: ${{ secrets.STUDIO_GITHUB_TOKEN }}
      - uses: cliffano/command-docker-action@v1.3.0
        with:
          image: cliffano/studio:2.9.0
          command: 'make deps gen-versions-list update-versions-list-gist'
          env_file: '/tmp/.env'
